#!/bin/bash

clear

source pacman

sudo rm /etc/makepkg.conf

sudo mv Makepkg/optimized-O3/makepkg.conf /etc/

sudo pacman-mirrors --fasttrack

sudo pacman -Syy archlinux-keyring manjaro-keyring --noconfirm

sudo pacman -Syy base-devel extra-cmake-modules ccache meson autoconf-archive make cmake yay --noconfirm

sudo pacman -S  heimdall android-tools libmtp android-udev --noconfirm

yay -S android-bash-completion adbfs-rootless-git adb-sync-git edl-git spflashtool5-bin --noconfirm

cd ..

rm -Rf manjaro

reboot
