#!/bin/bash

clear

rm /etc/makepkg.conf

mv makepkg/optimized-O3/makepkg.conf /etc/

pacman-mirrors --fasttrack

pacman -Syy archlinux-keyring manjaro-keyring --noconfirm

pacman -Syy base-devel extra-cmake-modules ccache meson autoconf-archive make cmake --noconfirm


echo '




                         Done  /   Готово


'
