#!/bin/bash

clear

source pacman

echo "






                       Hello !  Welcome to "Game install tools"

                            Install advanced tools ??
"
echo -e "\t
                        -> Install GWE (  1  )  "
echo -e "\
                        -> Install IntelPowerControl  (  2  )"
echo -e "\
                        -> Install CoreCtrl   (  3  )"
echo -e "\
                        -> Install GWE + IntelPowerControl  (  4  )"
echo -e "\
                        -> Install GWE + CoreCtrl (  5  )"
echo -e "\
                        -> Install IntelPowerContrl + CoreCtrl (  6  )"
echo -n "

                            -> Введите значение : "
read main_menu
      case "$main_menu" in
         "1" )
GWE=gwe
PI=python-injector
PP=python-py3nvml
         ;;
         "2" )
IPC=intel-power-control-git
         ;;
         "3" )
Core='sudo pacman -Sy corectrl --noconfirm'
         ;;
         "4" )
GWE=gwe
PI=python-injector
PP=python-py3nvml
IPC=intel-power-control-git
         ;;
         "5")
GWE=gwe
PI=python-injector
PP=python-py3nvml
Core='sudo pacman -Sy corectrl --noconfirm'
         ;;
         "6")
Core='sudo pacman -Sy corectrl --noconfirm'
IPC=intel-power-control-git
      esac
clear

sudo rm /etc/makepkg.conf

sudo mv Makepkg/optimized-O3/makepkg.conf /etc/

sudo pacman-mirrors --fasttrack

sudo pacman -Syy archlinux-keyring manjaro-keyring --noconfirm

sudo pacman -Syy base-devel extra-cmake-modules ccache meson autoconf-archive make cmake --noconfirm

sudo pacman -Sy haveged dbus-broker cpupower gamemode lib32-gamemode mangohud vkd3d irqbalance --noconfirm

curl -s https://api.github.com/repos/RusNor/Ported-version-of-MangoHud-and-vkBasalt/releases/latest | grep "install_gmv_utils_v" | cut -d : -f 2,3 | tr -d \" | wget -qi - || chmod +x $HOME/install_gmv_utils_v* && sh install_gmv_utils_v*

yay -S ananicy-cpp ananicy-rules antimicrox system-monitoring-center gconf lib32-gconf python-proxy_tools python-pywebview $PI $PP $GWE $IPC startwine linux-xanmod-bin --noconfirm

$Core
















