#!/bin/bash
clear

source pacman

sudo pacman-mirrors --fasttrack

sudo pacman -Syy archlinux-keyring manjaro-keyring --noconfirm

sudo pacman -Sy mesa mesa-demos lib32-mesa vulkan-radeon lib32-vulkan-radeon vulkan-icd-loader lib32-vulkan-icd-loader amf-headers libteam distorm hip-runtime-amd hsa-amd-aqlprofile-bin miopen-hip nvtop python-distorm python-pyamdgpuinfo xf86-video-amdgpu network-manager-applet mesa-utils mesa-vdpau vulkan-mesa-layers lib32-libva-mesa-driver lib32-mesa-demos lib32-mesa-utils lib32-mesa-vdpau lib32-vulkan-mesa-layers vulkan-tools vkd3d --noconfirm

cd ..

rm -Rf manjaro

reboot
