#!/bin/bash
clear
echo '



                ----------------------------------


                Welcome to Nvidia driver installer

                       Power by Linuxshef

                               ;)

                 ----------------------------------


'
