#!/bin/bash

clear

source pacman

sudo rm /etc/makepkg.conf

sudo mv ~/manjaro/Makepkg/optimized-O3/makepkg.conf /etc/

sudo pacman-mirrors --fasttrack

sudo pacman -Syy archlinux-keyring manjaro-keyring --noconfirm

sudo pacman -Syy base-devel extra-cmake-modules ccache meson autoconf-archive make cmake yay --noconfirm

yay -S linux-xanmod-bin --noconfirm

sudo mkinitcpio -p linux-xanmod

sudo mkinitcpio -p linux-xanmod

sudo update-grub

cd ~/

rm -Rf manjaro

reboot
